spreecity/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spreecity.views.home', name='home'),
    # url(r'^spreecity/', include('spreecity.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^user_management/',include('spreecity.user_management.urls')),
    
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',                        
                {'document_root': settings.STATIC_DOC_ROOT}),
                       
    (r'^$', 'django.views.generic.simple.redirect_to', {'url': '/admin'}),

)

spreecity/user_management/forms.py
from django.contrib.auth.models import User

from django import forms

class MemberForm(forms.Form):
    first_name          = forms.CharField()
    last_name           = forms.CharField()
    country             = forms.ChoiceField(choices = [('SINGAPORE','Singapore'),('SINGAPORE','Singapore')])
    city                = forms.ChoiceField(choices = [('SINGAPORE','Singapore'),('SINGAPORE','Singapore')])
    email               = forms.EmailField()
    password            = forms.CharField( widget=forms.PasswordInput)
    confirm_password    = forms.CharField( widget=forms.PasswordInput)
    date                = forms.ChoiceField(choices = [('1','1'),('2','2')])
    month               = forms.ChoiceField(choices = [('1','JAN'),('2','FEB')])
    year                = forms.ChoiceField(choices = [('1980','1980'),('1981','1981'),('1982','1982')])
    

    def clean_email(self):
        email = self.cleaned_data['email']
        user_check = User.objects.filter(email = email)
        if len(user_check) > 0:
            raise forms.ValidationError("Email already available in the system")
        return email
    
class PartnerForm(forms.Form):
    company_name            = forms.CharField()
    company_country         = forms.ChoiceField(choices = [('SINGAPORE','Singapore'),('SINGAPORE','Singapore')])
    business_name           = forms.CharField()
    business_type           = forms.ChoiceField(choices = [('FASHION','FASHION'),('IT','IT')])
    business_description    = forms.CharField(widget=forms.Textarea)
    mailling_address        = forms.CharField(widget=forms.Textarea)
    zipcode                 = forms.CharField()
    country                 = forms.ChoiceField(choices = [('SINGAPORE','Singapore'),('SINGAPORE','Singapore')])
    state                   = forms.CharField()
    city                    = forms.CharField()
    #email                   = forms.EmailField()
    #password                = forms.CharField( widget=forms.PasswordInput)
    #confirm_password        = forms.CharField( widget=forms.PasswordInput)
    #update                  = forms.BooleanField(label = 'I would like to receive updates from SpreeCity', initial = True)
    
    def clean_email(self):
        email = self.cleaned_data['email']
        user_check = User.objects.filter(email = email)
        if len(user_check) > 0:
            raise forms.ValidationError("Email already available in the system")
        return email

spreecity/templates/client_base.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
{{ block.super }}

<!--
<link type="text/css" href="/media/jquery-ui/css/ui-lightness/jquery-ui-1.8.12.custom.css" rel="stylesheet" />	
<script type="text/javascript" src="/media/jquery-ui/js/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="/media/jquery-ui/js/jquery-ui-1.8.12.custom.min.js"></script>
-->
<script type="text/javascript">
    // from http://www.quirksmode.org/js/detect.html
    var BrowserDetect = {
        init: function(){
            this.browser = this.searchString(this.dataBrowser) || "An unknown browser";
            this.version = this.searchVersion(navigator.userAgent) ||
            this.searchVersion(navigator.appVersion) ||
            "an unknown version";
            this.OS = this.searchString(this.dataOS) || "an unknown OS";
        },
        searchString: function(data){
            for (var i = 0; i < data.length; i++) {
                var dataString = data[i].string;
                var dataProp = data[i].prop;
                this.versionSearchString = data[i].versionSearch || data[i].identity;
                if (dataString) {
                    if (dataString.indexOf(data[i].subString) != -1) 
                        return data[i].identity;
                }
                else 
                    if (dataProp) 
                        return data[i].identity;
            }
        },
        searchVersion: function(dataString){
            var index = dataString.indexOf(this.versionSearchString);
            if (index == -1) 
                return;
            return parseFloat(dataString.substring(index + this.versionSearchString.length + 1));
        },
        dataBrowser: [{
            string: navigator.userAgent,
            subString: "Chrome",
            identity: "Chrome"
        }, {
            string: navigator.userAgent,
            subString: "OmniWeb",
            versionSearch: "OmniWeb/",
            identity: "OmniWeb"
        }, {
            string: navigator.vendor,
            subString: "Apple",
            identity: "Safari",
            versionSearch: "Version"
        }, {
            prop: window.opera,
            identity: "Opera"
        }, {
            string: navigator.vendor,
            subString: "iCab",
            identity: "iCab"
        }, {
            string: navigator.vendor,
            subString: "KDE",
            identity: "Konqueror"
        }, {
            string: navigator.userAgent,
            subString: "Firefox",
            identity: "Firefox"
        }, {
            string: navigator.vendor,
            subString: "Camino",
            identity: "Camino"
        }, { // for newer Netscapes (6+)
            string: navigator.userAgent,
            subString: "Netscape",
            identity: "Netscape"
        }, {
            string: navigator.userAgent,
            subString: "MSIE",
            identity: "Explorer",
            versionSearch: "MSIE"
        }, {
            string: navigator.userAgent,
            subString: "Gecko",
            identity: "Mozilla",
            versionSearch: "rv"
        }, { // for older Netscapes (4-)
            string: navigator.userAgent,
            subString: "Mozilla",
            identity: "Netscape",
            versionSearch: "Mozilla"
        }],
        dataOS: [{
            string: navigator.platform,
            subString: "Win",
            identity: "Windows"
        }, {
            string: navigator.platform,
            subString: "Mac",
            identity: "Mac"
        }, {
            string: navigator.userAgent,
            subString: "iPhone",
            identity: "iPhone/iPod"
        }, {
            string: navigator.platform,
            subString: "Linux",
            identity: "Linux"
        }]
    
    };
    BrowserDetect.init();
</script>

<script type="text/javascript"> 

function show_info(message) {
	html_str = '<p> <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>' + message + '</p>';
	$('#dialog-message').html(html_str);
		$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#dialog-message" ).dialog({
			modal: true,
			buttons: {
				Ok: function() {
					$( this ).dialog( "close" );
				}
			}
		});
	});

}	

function show_warning(message) {
	html_str = '<p> <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 50px 0;"></span>' + message + '</p>';
	$('#dialog-warning').html(html_str);
		$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#dialog-warning" ).dialog({
			modal: true,
			buttons: {
				Ok: function() {
					$( this ).dialog( "close" );
				}
			}
		});
	});

}	
</script> 
<script type="text/javascript" src="/media/js/core.js"></script> 
<script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script> 
<script type="text/javascript" src="/media/js/jquery.min.js"></script> 
<!--
<script type="text/javascript" src="/media/js/jquery.init.js"></script> 
<script type="text/javascript" src="/media/js/actions.min.js"></script>
--> 
<script type="text/javascript" src="/media/js/jquery-ui.min.js"></script>


{{ form.media }}
{% endblock %}

spreecity/templates/member.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>signup</title>

<link href="http://183.182.84.84/speercity/stylesheet.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" >

function save(){
	$('#id_member_creation').submit();
}

</script>
<style type="text/css">
 #id_date{
	background:url(images/d.o.b_bg.png) no-repeat !important;
	width:62px !important;
	height:22px !important;
}
 #id_month{
	background:url(images/d.o.b_bg.png) no-repeat !important;
	width:62px !important;
	height:22px !important;
}
 #id_year{
	background:url(images/d.o.b_bg.png) no-repeat !important;
	width:62px !important;
	height:22px !important;
}
</style>
</head>



<body>

<!--Wrapper Start Here-->

<div id="wrap">

<div id="signin">

<div class="signup_top"></div>

<div class="signup_mid">

	<div class="signup_head">

    <h2>New SpreeCity Members Sign Up</h2>
    <div class="close-btn"></div>

    </div>

    <div class="signup_content"> 	<div style="color:green;">{{error }}</div>We are currently in Beta. All signups are by-invite only.<br/><br/>If you wish to receive follow your favourite brands or receive exclusive 

privileges, request for an invite.<br/>

	<p>Are you representing a brand?</p>

    <a href="#" class="fl">Get your corporate account here.</a> <!--<span class="fl"><a href="#">Learn more</a></span>-->



</div>
		
     <div class="form">
					
              <form action="." method="post" name="member_creation" id="id_member_creation">{% csrf_token %}

                <div class="field required">

                  <label for="DisplayName">{{ form.first_name.label }}</label>

                 {{ form.first_name}}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.last_name.label }}</label>

                 {{ form.last_name }}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.country.label }} </label>

                  {{ form.country }}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.city.label }} </label>

                 {{ form.city }}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.email.label }}  </label>

				{{ form.email }}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.password.label }}</label>

                 {{ form.password }}

                </div>

                

                <div class="field required">

                  <label for="DisplayName" class="fl">{{ form.confirm_password.label }}</label>

				{{ form.confirm_password }}

                </div>

                <div>

                 <div class="field required fl dob_label">

                  <label for="DisplayName" class="fl dob_label">   {{ form.date.label  }} </label>

                  {{ form.date  }}

                </div>

                <div class="field required fl dob_label">

                  <label for="DisplayName" class="fl dob_label">   {{ form.month.label  }}</label>
					{{ form.month  }}

                </div>

                <div class="field required fl dob_label" >

                  <label for="DisplayName" class="fl dob_label">{{ form.year.label  }} </label>

                 {{ form.year  }}


                </div>

                <p style="clear:both;"></p>

                </div>

                 <div class="field required">

                  <label for="DisplayName" class="fl gender">gender </label>
	
                  <img src="http://183.182.84.84/speercity/images/gender.png" alt="" class="fl gender_img" />

                </div>
					
					<div class="signup-btn clr">

            <input type="submit" value="" name="bntSave" id="bntSave" onclick="javascipt:save();" title="click here to sign up" />

            </div>

			</form>

            
	</div>            

</div>

<div class="signup_btm"></div>

</div>

</div>

<!--Wrapper End Here-->

</body>

</html>

spreecity/templates/member_creation.html
{% extends "client_base.html" %}
{% block content %}
<link rel="stylesheet" href="/site_media/css/admin/jQuery/jquery.ui.all.css">

<script type="text/javascript" >


$(function(){
    $(document).ready(function(){

    });
});


</script>


<form action="." method="post" name="member_creation" id="id_member_creation">{% csrf_token %}
<h1>Member Creation</h1>
<br>
<label id="form_message" name="form_message">{{error}}</label>
<table summary="" id="member_table">
<tbody>
{% for field in form %}
<tr><td>{{field.label_tag}}</td><td>{{field}}</td><td>{{field.errors}}</td></tr>
{% endfor %}
</tbody>
</table>
<br>
<input type="submit" name="btnSave" id="bntSave" value="Save" />
</form>
{% endblock %}

spreecity/templates/member_creation122.html
{% extends "client_base.html" %}
{% block content %}
<link rel="stylesheet" href="/site_media/css/admin/jQuery/jquery.ui.all.css">
<link rel="stylesheet" href="/site_media/css/dashboard_table_rows.css">
<script type="text/javascript" src="/site_media/js/jquery-ui.min.js"></script>
<script type="text/javascript">
$(function(){
   $(document).ready(function(){
	   $(".dateclass").datepicker({"dateFormat": 'yy-mm-dd', changeMonth:true, changeYear:true});
	   });

   $("#selectall").click(function () {
		  $('.case').attr('checked', this.checked);
	});
   $(".case").click(function(){
		if($(".case").length == $(".case:checked").length) {
			$("#selectall").attr("checked", "checked");
		} else {
			$("#selectall").removeAttr("checked");
		}
	});

   $("#id_invoice").submit(function() {
	   if($("#id_customer").val() == "") {
	   		alert("Please select member name");
	   		return false;
	   		}

	  if($("#from_date").val() == "") {
	   		alert("Please select from date");
	   		return false;
	   		}

	   if($("#to_date").val() == "") {
	   		alert("Please select to date");
	   		return false;
	   		}
   });
   $(".convert_invoice").click(function(){
	   if ($("input[name='choices']").serializeArray().length == 0) {
	     	alert('Please select orders to convert to invoice');
	     	return false;
	   		}
   });
$("#id_customer").val("{{ member_id }}");
$("#id_department").val("{{ beneficiary_department }}");
});   				
</script>
<form name = "invoice" id = "id_invoice" action="." method="POST" ">{% csrf_token %}  
		Customer Name: <select name="customer" id = "id_customer" selected="True">
					  	<option value="">-----------------</option> 
	    					{% for member in members %}
						    	<option value= {{ member.id }}>{{ member.email }}</option>
							{% endfor %}
					   </select>
		

		Department: <select name = "department" id = "id_department">
					<option value = "">-----------------</option> 
 						{% for beneficiary in beneficiarys %}
	    					<option value = "{{ beneficiary.department }}">{{ beneficiary.department }}</option>
						{% endfor %}
					</select>

		From Date:<input type="text" size="10" id="from_date" name="from_date" value = "{{from_date}}" class = "dateclass" />
		To Date:  <input type="text" size="10"  id="to_date" name="to_date" value = "{{to_date}}" class = "dateclass"/>
				  <input type="submit" value="Generate" name = "generate" /><br><br><br>

			<table width="100%">
				<thead>
					<tr class="dasboard_table_header">
						<th> <input type="checkbox" name="master"  value="head" id="selectall" /> </th>
						<th> Order Number 		  </th>
						<th> Order Date   		  </th>
						<th> Member ID 	  </th>
						<th> Member Login ID </th> 
	                    <th> Net Amount			  </th> 
	                </tr>
					<tr class="dasboard_table_header">
						{% if order_generation|length > 0 %}
					      		{% for order in order_generation %}
									<th> <input type="checkbox" name="choices" value={{order.id}} class="case"  /> </th>
									<th> <a href="/dashboard/delivery_management/ordergeneration/{{order.id}}/"    id = {{order.id}} > {{order.id}}	</a> </th>
									<th> {{order.delivery_date}} 																						 </th>
									<th> {{member.id}}			 																						 </th>
									<th> {{member.email}} 		 																						 </th>
			                        <th> {{order.total_price}}	 																						 </th> 
			          				</tr> 	
			                	{% endfor %}
			            {% else %}
			            	<tr><td colspan="11"> No Regards Found </td></tr>
			            {% endif %}	
	 			</thead>
	 		</table><br><br>
 				<input type="submit" value="Convert to Invoice" name = "convertinvoice" class = "convert_invoice" />
</form>
{% endblock %}

spreecity/templates/partner_creation.html
{% extends "client_base.html" %}
{% block content %}
<link rel="stylesheet" href="/site_media/css/admin/jQuery/jquery.ui.all.css">

<script type="text/javascript" >


$(function(){
    $(document).ready(function(){

    });
});


</script>


<form action="." method="post" name="partner_creation" id="id_partner_creation">{% csrf_token %}
<h1>Partner Creation</h1>
<br>
<label id="form_message" name="form_message">{{error}}</label>
<br>
<table summary="" id="partner_table">
<tbody>
{% for field in form %}
<tr><td>{{field.label_tag}}</td><td>{{field}}</td><td>{{field.errors}}</td></tr>
{% endfor %}
</tbody>
</table>
<br>
<input type="submit" name="btnSave" id="bntSave" value="Save" />
</form>
{% endblock %}

spreecity/templates/signup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Partner's Sign Up</title>

<link href="http://183.182.84.84/speercity/stylesheet.css" rel="stylesheet" type="text/css" />

</head>



<body>

<!--Wrapper Start Here-->

<div id="wrap1">

<div id="signupprocess">

<div class="signupprocess_top"></div>

<div class="signupprocess_mid">

	<div class="signupprocess_head">

    <h2>Partner's Sign Up</h2>

    <div class="close-btn"></div>

    </div><span class="clr"></span>
		
    <!--nav start-->
		
    <div class="signupprocess_nav">

    <ul>

    <li><a href="#" class="selected">Information</a></li>

    <li><a href="#"> Account</a></li>

    <li><a href="#">Plan Selection</a></li>

    <li><a href="#">Billing Info</a></li>

    <li class="last"><a href="#">Confirmation</a></li>

    </ul>

    </div>

    <!--nav end-->

   

     <div class="informationform">

              <form action="." method="post" name="partner_creation" id="id_partner_creation">{% csrf_token %}

					<div style="color:green;">{{error }}</div> 
              <div class="leftinformationform fl">

              <p class="signupprocess_content">COMPANY INFORMATION <span>(not visible to public)</span></p>

                <div class="field required fl">

                  <label for="DisplayName">{{ form.company_name.label }} 	</label>

                  {{ form.company_name }}

                </div>

                

                <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.company_country.label }} </label>

                   {{ form.company_country }}

                </div>

                <p class="signupprocess_content fl">BUSINESS INFORMATION <span>(visble to public)</span>



</p>



                 <div class="field formrequired fl">

                  <label for="DisplayName">{{ form.business_name.label }}</label>

                 {{ form.business_name }}

                </div>

                

                 <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.business_type.label }} </label>

                  {{ form.business_type }}

                </div>

                

                 <div class="field formrequired fl">

                  <label for="DisplayName">{{ form.business_description.label }}	</label>

                 {{ form.business_description }}
                </div>

                

                </div>

                

                <div class="rightinformationform fr">

                

                 <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.mailling_address.label }} </label>

                  {{ form.mailling_address }}
                </div>

                

                 <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.zipcode.label }} </label>

                 {{ form.zipcode }}
                </div>

                

                <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.country.label }} </label>

                  {{ form.country }}

                </div>

                

                <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.state.label }} </label>

                  {{ form.state }}

                </div>

               

                <div class="field formrequired">

                  <label for="DisplayName" class="fl">{{ form.city.label }}</label>

                  {{ form.city }}

                </div>

              

                <p style="clear:both;"></p>

                </div>

                 <div class="field formrequired">

                  <label for="DisplayName" class="fl yesno">I would like to receive updates from SpreeCity. </label>

                  <img src="http://183.182.84.84/speercity/images/yesno.png" alt="" class="fl yesno_img" />

                </div>
					
					<div class="next-btn clr">

            <input type="submit" value="" title="click here to next" />

            </div>

			</form>

            
	</div>            

</div>

<div class="signupprocess_btm"></div>

</div>

</div>

<!--Wrapper End Here-->

</body>

</html>